### ISSUE TITLE
WWDC 15 Scholarship Rule

### ISSUE THREAD

**Issue by TosinAF** [eddiekaiger/PortfolioApp#1]
The name of the app is meant to be your first name & last name. Currently it is set to 'portfolio'. The rules are listed at https://developer.apple.com/wwdc/scholarships/Scholarship-Guidelines-and-Terms.pdf

Goodluck man!

**Comment by eddiekaiger** [comment]
Thanks, man! I planned on changing it before submitting, but thanks for the reminder :)
